# Generated by Django 3.1.3 on 2020-11-08 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs_', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogpost',
            old_name='date_add',
            new_name='date_added',
        ),
    ]
